module_name: Block User Info
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - login
  - user information
  - customer login
description_short: The block user info block adds a login link to the top of your site
description: description.md
images:
  - image-1.png
license: AFL
